### PR TITLE
Fix chat errors

### PR DESCRIPTION
**Pull request by francisbrito**

### CODE REVIEW

**Comment by francisbrito** [comment]
There seems to be code style guide issues with the project which makes StyleCI complain *a lot* about my last commit. Most errors are in files that I haven't changed, so maybe we should open up an issue for fixing them. Any thoughts ? @ryanhowdy

**Comment by ryanhowdy** [comment]
Sorry about the slow reply.

Yea those failures can be ignored, I have been meaning to remove them.

I haven't merged these changes in yet for two reasons.

1)  This needs merged into 3.6.0 and not into master.
2)  As part of this fix, I think we need to upgrade the AJAX Chat module to the latest version.  That may fix all or most of these problems anyway.

**Comment by francisbrito** [comment]
Closing this, as it was made in the wrong branch. 

About point 2: How should we proceed to update the AJAX Chat module?

**Comment by ryanhowdy** [comment]
I just updated this, this weekend.

Issue #465 

If you want to test it out, you should be able to download the 3.5.1 branch and just copy over all the files to your directory.  No database changes are needed.

**Pull request closed without merging**
