### PR TITLE
Config to build a docker image

### PR DESCRIPTION
**Pull request by leolivier**
This is a set of files for 
1. creating a docker image of fcms
2. running easily nginx+mariadb+fcms using docker compose

See details in [README.docker.md](README.docker.md)

Next steps is to automate the init phases

### CODE REVIEW

**Comment by leolivier** [comment]
Looks like the issue in scrutinizer is not on my side... Can't do anything on that.
Furthermore I mainly disagree with the error found by the static code analysis, and especially on the package version in the Dockerfile. And there is no way to bypass them :/ I'll fix the other ones, not the one on the packages...

**Comment by ryanhowdy** [comment]
I've removed all the ci checks. Those were old and misconfigured.

**Comment by leolivier** [comment]
Thanks Ryan. Updated the PR with automated setup right now.
If someone can check it works fine, would be great. I tested it on my side and I obtained more or less the same level of features that the "usual" fcms version.

**Comment by leolivier** [comment]
Canceling this PR, please use the other one on a clean branch

**Pull request closed without merging**
